CREATE TABLE `oauth2_tokens` (
	`id` int AUTO_INCREMENT NOT NULL,
	`userId` int NOT NULL,
	`platform` varchar(64) NOT NULL,
	`accessToken` text NOT NULL,
	`refreshToken` text,
	`idToken` text,
	`tokenType` varchar(32) NOT NULL DEFAULT 'Bearer',
	`expiresAt` timestamp NOT NULL,
	`scope` text,
	`state` varchar(255),
	`codeVerifier` varchar(255),
	`accountId` varchar(255) NOT NULL,
	`accountEmail` varchar(320),
	`accountName` varchar(255),
	`profilePicture` text,
	`isActive` int NOT NULL DEFAULT 1,
	`lastRefreshedAt` timestamp,
	`refreshAttempts` int NOT NULL DEFAULT 0,
	`lastRefreshError` text,
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	`updatedAt` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT `oauth2_tokens_id` PRIMARY KEY(`id`)
);
